services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'  
    env_file:
      - .env  
    environment:
      - NODE_ENV=production
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_KEY=${JWT_KEY}
      - TMDB_BASE_URL=${TMDB_BASE_URL}
      - TMDB_TOKEN=${TMDB_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

